### ISSUE TITLE
Running the plugin generates empty Spec frame

### ISSUE THREAD

**Issue by bochenn** [EightShapes/specs-plugin-feedback#28]
### Description

Every time I run the plugin it will render an empty frame with the name Specs. I tried this in different project files, starting from scratch a new component, on an empty page, etc. Nothing seems to work.

### Steps to reproduce
https://share.cleanshot.com/xMYJPFl8

**Comment by nathanacurtis** [comment]
@bochenn The plugin works only on nodes of type `instance` or `frame`. You are running it on a selection of instance `component`. For now, create an instance of the component and running the command on that. I've created a clean issue #29 to reflect this known issue.
