### ISSUE TITLE
Avoid including publishable styles in Figma file

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/specs-plugin-feedback#30]
### Problem statement

Users would prefer that the plug in not add styles to a library file, because they present as publishable styles.

### Solution

- Prepend style names with `.` so they are hidden from publishing by default?
- Offer a configuration (when configurations are supported) to apply styles directly rather than via style?

**Comment by snak10** [comment]
Yes, echoing that, we just got our hands on this plugin as a company, but every time we publish, we need to delete the styles, looks like an unnecessary style to exist in the DS file.

**Comment by nathanacurtis** [comment]
@snak10 You _could_ spec things in a different file (as all my clients do). 🤷

**Comment by snak10** [comment]
Yeah I could, and still looks like something that could be opted out, like many designers in my org said it, I’m just voicing the concern, the pain of deleting the styles once the plugin created the styles is way smaller than not using the plugin, that was just a feedback take it or not.

**Comment by nathanacurtis** [comment]
Another request from Figma community 
https://www.figma.com/@mikaelce
![image](https://user-images.githubusercontent.com/1165904/219658629-04755472-cd0e-43ae-a496-bd86985ee2d6.png)

**Comment by nathanacurtis** [comment]
Another comment
![image](https://user-images.githubusercontent.com/1165904/219681657-a3ff0513-bd50-4f1d-9fdf-7f6a2867da6d.png)

**Comment by nathanacurtis** [comment]
Another comment:
![image](https://user-images.githubusercontent.com/1165904/219681851-29f1eeb3-ee74-4f15-a59f-76c2bbd63236.png)
