### ISSUE TITLE
Does not work with SAP Stencils

### ISSUE THREAD

**Issue by ravidaloni** [EightShapes/specs-plugin-feedback#33]
I downloaded the stencils and tried it with the plugin, but it does not work :-( It does not produce specs :-(

**Comment by nathanacurtis** [comment]
Are you referring to [SAP EXTERNAL Fiori Web Stencils v1.96](https://www.figma.com/community/file/1058214955555969809)?

If so, can you be more specific about the component(s) you ran it on? Was there an error message in the Plugins > Development > Open console?

**Comment by ravidaloni** [comment]
Dear Nathan,

my mistake!

One needs to drag an asset from the library and not just select the component.

Best!
Ravid
