### ISSUE TITLE
Itemize frames with non-default, non-varying attributes as elements in anatomy

### ISSUE THREAD

**Issue by inetwebguy** [EightShapes/specs-plugin-feedback#34]
When creating some components, I do not add a "rectangle or another layer in the background to serve that purpose. i.e. a frame with a BG fill, radius, box shadow, etc.. applied to the frame is not included in the specs unless I add a rectangle to eh frame and apply those decisions to a rectangle.

I would like to see a spec for decisions applied to the frame itself.

As mentioned, I can add a rectangle to the frame and apply the design decisions to the rectangle, but that's not how it would be done in code.

The image attached shows the results of running the plugin with color, radius, and box shadow applied to the frame (auto-layout)

<img width="929" alt="Screenshot 2023-02-14 at 7 01 56 PM" src="https://user-images.githubusercontent.com/16294046/218890954-1e3e7252-9887-427e-bdee-1adfe38a3e8d.png">

**Comment by nathanacurtis** [comment]
@inetwebguy,

Thanks for your interest and submitting your issue. I agree, the plugin should be picking up attributes on the top layer of the selected node (as confirmed in my example here, `Frame 1`).

![image](https://user-images.githubusercontent.com/1165904/219021848-69fa22dc-b43a-415c-932f-1cd28d425aa1.png)
