### ISSUE TITLE
Selecting a component could fail better

### ISSUE THREAD

**Issue by NoWorries** [EightShapes/specs-plugin-feedback#35]
### Description

It wasn't immediately clear if i could just select a component set and get the results. It still runs, but the results are empty. Could it be more helpful to warn if a component or component set is selected, and advise the user to just select an Instance or Frame?

### Steps to reproduce

1. Select a component
2. Run the plugin
3. Creates the Autolayout "Specs" layer

### Expected behavior

When you don't select anything, you get told to select a frame or an instance. So i had to assume that selecting a component is not the intention. Could this just be an error when selecting a component instead of trying to process it and it not working?

### Screenshot
<img width="348" alt="image (1)" src="https://user-images.githubusercontent.com/803064/218919564-6cf9bf98-c948-4674-9d42-ff485511e773.png">

**Comment by nathanacurtis** [comment]
@NoWorries,

While I may tackle #29 at some point soon (the wiring needed isn't trivial), would failing the entire run (even if other nodes _aren't_ components) and this error message suffice?

![image](https://user-images.githubusercontent.com/1165904/219015229-a4dbc0f0-2884-4e20-bd7b-3fea3f1264f5.png)
