### ISSUE TITLE
Border Radius Properties Not Show Up 

### ISSUE THREAD

**Issue by geekfast** [EightShapes/specs-plugin-feedback#36]
**Layout and Spacing**
missing Border radius properties

**Comment by nathanacurtis** [comment]
@geekfast Could you provide details on your case, such as how your component is built and plugin outputs, so that I can diagnose where the issue is. If it's the same issue as #34, you can close this issue.

**Comment by nathanacurtis** [comment]
@geekfast After fixing #34, I'm confident this resolves your problem (a `border-radius` attribute shown on a frame layer or top-layer of an instance).

**Comment by nathanacurtis** [comment]
Closing as resolved.
