### ISSUE TITLE
Padding Value 

### ISSUE THREAD

**Issue by geekfast** [EightShapes/specs-plugin-feedback#37]
Individual padding value can merge into 1 general padding value (if has same value)

padding: X

instead of
padding-left: X
padding-top: X
padding-right: X
padding-bottom: X

**Comment by nathanacurtis** [comment]
@geekfast I will look into this. `padding` (along with `corner-radius` and `strokeWeight`) are all already setup to consolidate the display into a single attribute when equal on all four sides. If you have a Figma sample you could provide view access (that I could duplicate) as a test case or a deeper set of screenshots revealing your build and plugin output, that'd be great.

**Comment by nathanacurtis** [comment]
Defect confirmed. Fixing to consolidate `Padding` when all four sides are equal.
![image](https://user-images.githubusercontent.com/1165904/219395452-fd13b043-9257-4ccd-8ccf-5054cd10f6d4.png)
