### ISSUE TITLE
Error: height <= 0 when spec'ing elements for Autolayout

### ISSUE THREAD

**Issue by C3PablO** [EightShapes/specs-plugin-feedback#38]
### Description

The plugin gets stuck at running stage after generating some frames. The frames overlap each other. 

### Steps to reproduce

1. Drag Button instance to the canvas
3. Run the plugin

### Expected behavior
Successful run or error message

### Screenshot

<img width="455" alt="Screenshot 2023-02-16 at 12 38 51" src="https://user-images.githubusercontent.com/3966942/219355480-cc14a78a-6419-4374-99f4-eb21ae1da547.png">

### Console log

figma_app.min.js.br:1419 Console was cleared
figma_app.min.js.br:5 ------- Clearing and silencing console.log from Figma -------
figma_app.min.js.br:5 unhandled promise rejection: Error: in resize: Expected "height" to have value >= 0.01
(anonymous) @ figma_app.min.js.br:5
printChar @ jsvm-cpp.js.br:9
_fd_write @ jsvm-cpp.js.br:9
$func798 @ jsvm-cpp.wasm.br:0x8380e
$func802 @ jsvm-cpp.wasm.br:0x83aac
$func811 @ jsvm-cpp.wasm.br:0x852b6
$func812 @ jsvm-cpp.wasm.br:0x852d7
$func13 @ jsvm-cpp.wasm.br:0x1210
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6188
(anonymous) @ figma_app.min.js.br:551
Promise.then (async)
c @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:580
(anonymous) @ figma_app.min.js.br:1419
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1419
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1419
(anonymous) @ figma_app.min.js.br:1392
(anonymous) @ figma_app.min.js.br:1274
JCu.e.invokeCallback @ figma_app.min.js.br:551
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func203 @ jsvm-cpp.wasm.br:0x29e7e
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func490 @ jsvm-cpp.wasm.br:0x549a5
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6036
(anonymous) @ figma_app.min.js.br:551
Promise.then (async)
c @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:580
(anonymous) @ figma_app.min.js.br:1419
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1419
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1419
(anonymous) @ figma_app.min.js.br:1392
(anonymous) @ figma_app.min.js.br:1274
JCu.e.invokeCallback @ figma_app.min.js.br:551
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func204 @ jsvm-cpp.wasm.br:0x29fd9
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func624 @ jsvm-cpp.wasm.br:0x6de94
$func138 @ jsvm-cpp.wasm.br:0x13819
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func332 @ jsvm-cpp.wasm.br:0x38d9d
$func172 @ jsvm-cpp.wasm.br:0x25044
$func336 @ jsvm-cpp.wasm.br:0x39ac1
$jsvm_evalCode @ jsvm-cpp.wasm.br:0xb0b8
evalCode @ figma_app.min.js.br:551
evalCodeInternal @ figma_app.min.js.br:581
evalTopLevelCode @ figma_app.min.js.br:582
(anonymous) @ figma_app.min.js.br:1421
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
runResult @ figma_app.min.js.br:1421
gCs @ figma_app.min.js.br:1419
await in gCs (async)
qfr @ figma_app.min.js.br:1424
(anonymous) @ figma_app.min.js.br:1554
await in (anonymous) (async)
j2t @ figma_app.min.js.br:1554
Hrp @ figma_app.min.js.br:1554
await in Hrp (async)
(anonymous) @ figma_app.min.js.br:1554
m3 @ figma_app.min.js.br:2000
(anonymous) @ figma_app.min.js.br:2221
c.port1.onmessage @ VM6:2
figma_app.min.js.br:5     at B (PLUGIN_9_SOURCE)
(anonymous) @ figma_app.min.js.br:5
printChar @ jsvm-cpp.js.br:9
_fd_write @ jsvm-cpp.js.br:9
$func798 @ jsvm-cpp.wasm.br:0x8380e
$func896 @ jsvm-cpp.wasm.br:0x8d485
$func804 @ jsvm-cpp.wasm.br:0x84439
$func803 @ jsvm-cpp.wasm.br:0x843fd
$func802 @ jsvm-cpp.wasm.br:0x83a96
$func811 @ jsvm-cpp.wasm.br:0x852b6
$func812 @ jsvm-cpp.wasm.br:0x852d7
$func13 @ jsvm-cpp.wasm.br:0x125a
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6188
(anonymous) @ figma_app.min.js.br:551
Promise.then (async)
c @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:580
(anonymous) @ figma_app.min.js.br:1419
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1419
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1419
(anonymous) @ figma_app.min.js.br:1392
(anonymous) @ figma_app.min.js.br:1274
JCu.e.invokeCallback @ figma_app.min.js.br:551
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func203 @ jsvm-cpp.wasm.br:0x29e7e
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func490 @ jsvm-cpp.wasm.br:0x549a5
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6036
(anonymous) @ figma_app.min.js.br:551
Promise.then (async)
c @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:580
(anonymous) @ figma_app.min.js.br:1419
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1419
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1419
(anonymous) @ figma_app.min.js.br:1392
(anonymous) @ figma_app.min.js.br:1274
JCu.e.invokeCallback @ figma_app.min.js.br:551
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func204 @ jsvm-cpp.wasm.br:0x29fd9
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func624 @ jsvm-cpp.wasm.br:0x6de94
$func138 @ jsvm-cpp.wasm.br:0x13819
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func332 @ jsvm-cpp.wasm.br:0x38d9d
$func172 @ jsvm-cpp.wasm.br:0x25044
$func336 @ jsvm-cpp.wasm.br:0x39ac1
$jsvm_evalCode @ jsvm-cpp.wasm.br:0xb0b8
evalCode @ figma_app.min.js.br:551
evalCodeInternal @ figma_app.min.js.br:581
evalTopLevelCode @ figma_app.min.js.br:582
(anonymous) @ figma_app.min.js.br:1421
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
runResult @ figma_app.min.js.br:1421
gCs @ figma_app.min.js.br:1419
await in gCs (async)
qfr @ figma_app.min.js.br:1424
(anonymous) @ figma_app.min.js.br:1554
await in (anonymous) (async)
j2t @ figma_app.min.js.br:1554
Hrp @ figma_app.min.js.br:1554
await in Hrp (async)
(anonymous) @ figma_app.min.js.br:1554
m3 @ figma_app.min.js.br:2000
(anonymous) @ figma_app.min.js.br:2221
c.port1.onmessage @ VM6:2
figma_app.min.js.br:5     at addProp (PLUGIN_9_SOURCE)
(anonymous) @ figma_app.min.js.br:5
printChar @ jsvm-cpp.js.br:9
_fd_write @ jsvm-cpp.js.br:9
$func798 @ jsvm-cpp.wasm.br:0x8380e
$func896 @ jsvm-cpp.wasm.br:0x8d485
$func804 @ jsvm-cpp.wasm.br:0x84439
$func803 @ jsvm-cpp.wasm.br:0x843fd
$func802 @ jsvm-cpp.wasm.br:0x83a96
$func811 @ jsvm-cpp.wasm.br:0x852b6
$func812 @ jsvm-cpp.wasm.br:0x852d7
$func13 @ jsvm-cpp.wasm.br:0x125a
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6188
(anonymous) @ figma_app.min.js.br:551
Promise.then (async)
c @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:580
(anonymous) @ figma_app.min.js.br:1419
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1419
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1419
(anonymous) @ figma_app.min.js.br:1392
(anonymous) @ figma_app.min.js.br:1274
JCu.e.invokeCallback @ figma_app.min.js.br:551
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func203 @ jsvm-cpp.wasm.br:0x29e7e
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func490 @ jsvm-cpp.wasm.br:0x549a5
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6036
(anonymous) @ figma_app.min.js.br:551
Promise.then (async)
c @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:580
(anonymous) @ figma_app.min.js.br:1419
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1419
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1419
(anonymous) @ figma_app.min.js.br:1392
(anonymous) @ figma_app.min.js.br:1274
JCu.e.invokeCallback @ figma_app.min.js.br:551
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func204 @ jsvm-cpp.wasm.br:0x29fd9
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func624 @ jsvm-cpp.wasm.br:0x6de94
$func138 @ jsvm-cpp.wasm.br:0x13819
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func332 @ jsvm-cpp.wasm.br:0x38d9d
$func172 @ jsvm-cpp.wasm.br:0x25044
$func336 @ jsvm-cpp.wasm.br:0x39ac1
$jsvm_evalCode @ jsvm-cpp.wasm.br:0xb0b8
evalCode @ figma_app.min.js.br:551
evalCodeInternal @ figma_app.min.js.br:581
evalTopLevelCode @ figma_app.min.js.br:582
(anonymous) @ figma_app.min.js.br:1421
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
runResult @ figma_app.min.js.br:1421
gCs @ figma_app.min.js.br:1419
await in gCs (async)
qfr @ figma_app.min.js.br:1424
(anonymous) @ figma_app.min.js.br:1554
await in (anonymous) (async)
j2t @ figma_app.min.js.br:1554
Hrp @ figma_app.min.js.br:1554
await in Hrp (async)
(anonymous) @ figma_app.min.js.br:1554
m3 @ figma_app.min.js.br:2000
(anonymous) @ figma_app.min.js.br:2221
c.port1.onmessage @ VM6:2
figma_app.min.js.br:5     at P (PLUGIN_9_SOURCE)
(anonymous) @ figma_app.min.js.br:5
printChar @ jsvm-cpp.js.br:9
_fd_write @ jsvm-cpp.js.br:9
$func798 @ jsvm-cpp.wasm.br:0x8380e
$func896 @ jsvm-cpp.wasm.br:0x8d485
$func804 @ jsvm-cpp.wasm.br:0x84439
$func803 @ jsvm-cpp.wasm.br:0x843fd
$func802 @ jsvm-cpp.wasm.br:0x83a96
$func811 @ jsvm-cpp.wasm.br:0x852b6
$func812 @ jsvm-cpp.wasm.br:0x852d7
$func13 @ jsvm-cpp.wasm.br:0x125a
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6188
(anonymous) @ figma_app.min.js.br:551
Promise.then (async)
c @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:580
(anonymous) @ figma_app.min.js.br:1419
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1419
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1419
(anonymous) @ figma_app.min.js.br:1392
(anonymous) @ figma_app.min.js.br:1274
JCu.e.invokeCallback @ figma_app.min.js.br:551
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func203 @ jsvm-cpp.wasm.br:0x29e7e
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func490 @ jsvm-cpp.wasm.br:0x549a5
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6036
(anonymous) @ figma_app.min.js.br:551
Promise.then (async)
c @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:580
(anonymous) @ figma_app.min.js.br:1419
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1419
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1419
(anonymous) @ figma_app.min.js.br:1392
(anonymous) @ figma_app.min.js.br:1274
JCu.e.invokeCallback @ figma_app.min.js.br:551
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func204 @ jsvm-cpp.wasm.br:0x29fd9
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func624 @ jsvm-cpp.wasm.br:0x6de94
$func138 @ jsvm-cpp.wasm.br:0x13819
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func332 @ jsvm-cpp.wasm.br:0x38d9d
$func172 @ jsvm-cpp.wasm.br:0x25044
$func336 @ jsvm-cpp.wasm.br:0x39ac1
$jsvm_evalCode @ jsvm-cpp.wasm.br:0xb0b8
evalCode @ figma_app.min.js.br:551
evalCodeInternal @ figma_app.min.js.br:581
evalTopLevelCode @ figma_app.min.js.br:582
(anonymous) @ figma_app.min.js.br:1421
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
runResult @ figma_app.min.js.br:1421
gCs @ figma_app.min.js.br:1419
await in gCs (async)
qfr @ figma_app.min.js.br:1424
(anonymous) @ figma_app.min.js.br:1554
await in (anonymous) (async)
j2t @ figma_app.min.js.br:1554
Hrp @ figma_app.min.js.br:1554
await in Hrp (async)
(anonymous) @ figma_app.min.js.br:1554
m3 @ figma_app.min.js.br:2000
(anonymous) @ figma_app.min.js.br:2221
c.port1.onmessage @ VM6:2
figma_app.min.js.br:5     at <anonymous> (PLUGIN_9_SOURCE)
(anonymous) @ figma_app.min.js.br:5
printChar @ jsvm-cpp.js.br:9
_fd_write @ jsvm-cpp.js.br:9
$func798 @ jsvm-cpp.wasm.br:0x8380e
$func896 @ jsvm-cpp.wasm.br:0x8d485
$func804 @ jsvm-cpp.wasm.br:0x84439
$func803 @ jsvm-cpp.wasm.br:0x843fd
$func802 @ jsvm-cpp.wasm.br:0x83a96
$func811 @ jsvm-cpp.wasm.br:0x852b6
$func812 @ jsvm-cpp.wasm.br:0x852d7
$func13 @ jsvm-cpp.wasm.br:0x125a
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6188
(anonymous) @ figma_app.min.js.br:551
Promise.then (async)
c @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:580
(anonymous) @ figma_app.min.js.br:1419
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1419
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1419
(anonymous) @ figma_app.min.js.br:1392
(anonymous) @ figma_app.min.js.br:1274
JCu.e.invokeCallback @ figma_app.min.js.br:551
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func203 @ jsvm-cpp.wasm.br:0x29e7e
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func490 @ jsvm-cpp.wasm.br:0x549a5
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6036
(anonymous) @ figma_app.min.js.br:551
Promise.then (async)
c @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:580
(anonymous) @ figma_app.min.js.br:1419
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1419
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1419
(anonymous) @ figma_app.min.js.br:1392
(anonymous) @ figma_app.min.js.br:1274
JCu.e.invokeCallback @ figma_app.min.js.br:551
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func204 @ jsvm-cpp.wasm.br:0x29fd9
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func624 @ jsvm-cpp.wasm.br:0x6de94
$func138 @ jsvm-cpp.wasm.br:0x13819
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func332 @ jsvm-cpp.wasm.br:0x38d9d
$func172 @ jsvm-cpp.wasm.br:0x25044
$func336 @ jsvm-cpp.wasm.br:0x39ac1
$jsvm_evalCode @ jsvm-cpp.wasm.br:0xb0b8
evalCode @ figma_app.min.js.br:551
evalCodeInternal @ figma_app.min.js.br:581
evalTopLevelCode @ figma_app.min.js.br:582
(anonymous) @ figma_app.min.js.br:1421
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
runResult @ figma_app.min.js.br:1421
gCs @ figma_app.min.js.br:1419
await in gCs (async)
qfr @ figma_app.min.js.br:1424
(anonymous) @ figma_app.min.js.br:1554
await in (anonymous) (async)
j2t @ figma_app.min.js.br:1554
Hrp @ figma_app.min.js.br:1554
await in Hrp (async)
(anonymous) @ figma_app.min.js.br:1554
m3 @ figma_app.min.js.br:2000
(anonymous) @ figma_app.min.js.br:2221
c.port1.onmessage @ VM6:2
figma_app.min.js.br:5 
(anonymous) @ figma_app.min.js.br:5
printChar @ jsvm-cpp.js.br:9
_fd_write @ jsvm-cpp.js.br:9
$func798 @ jsvm-cpp.wasm.br:0x8380e
$func802 @ jsvm-cpp.wasm.br:0x83aac
$func811 @ jsvm-cpp.wasm.br:0x852b6
$func812 @ jsvm-cpp.wasm.br:0x852d7
$func13 @ jsvm-cpp.wasm.br:0x125a
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6188
(anonymous) @ figma_app.min.js.br:551
Promise.then (async)
c @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:580
(anonymous) @ figma_app.min.js.br:1419
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1419
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1419
(anonymous) @ figma_app.min.js.br:1392
(anonymous) @ figma_app.min.js.br:1274
JCu.e.invokeCallback @ figma_app.min.js.br:551
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func203 @ jsvm-cpp.wasm.br:0x29e7e
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func490 @ jsvm-cpp.wasm.br:0x549a5
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6036
(anonymous) @ figma_app.min.js.br:551
Promise.then (async)
c @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:551
get undefined @ figma_app.min.js.br:580
(anonymous) @ figma_app.min.js.br:1419
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1419
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1419
(anonymous) @ figma_app.min.js.br:1392
(anonymous) @ figma_app.min.js.br:1274
JCu.e.invokeCallback @ figma_app.min.js.br:551
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func204 @ jsvm-cpp.wasm.br:0x29fd9
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func624 @ jsvm-cpp.wasm.br:0x6de94
$func138 @ jsvm-cpp.wasm.br:0x13819
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func332 @ jsvm-cpp.wasm.br:0x38d9d
$func172 @ jsvm-cpp.wasm.br:0x25044
$func336 @ jsvm-cpp.wasm.br:0x39ac1
$jsvm_evalCode @ jsvm-cpp.wasm.br:0xb0b8
evalCode @ figma_app.min.js.br:551
evalCodeInternal @ figma_app.min.js.br:581
evalTopLevelCode @ figma_app.min.js.br:582
(anonymous) @ figma_app.min.js.br:1421
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
runResult @ figma_app.min.js.br:1421
gCs @ figma_app.min.js.br:1419
await in gCs (async)
qfr @ figma_app.min.js.br:1424
(anonymous) @ figma_app.min.js.br:1554
await in (anonymous) (async)
j2t @ figma_app.min.js.br:1554
Hrp @ figma_app.min.js.br:1554
await in Hrp (async)
(anonymous) @ figma_app.min.js.br:1554
m3 @ figma_app.min.js.br:2000
(anonymous) @ figma_app.min.js.br:2221
c.port1.onmessage @ VM6:2
figma_app.min.js.br:12 [Violation] 'requestAnimationFrame' handler took 72ms

**Comment by nathanacurtis** [comment]
@C3PablO Looks like `height` is set to zero on one or more elements when the **Layout and spacing** section identifies a layer with autolayout settings. Is that the case? Any chance you could provide view access to a Figma file with the offending instance?

**Comment by C3PablO** [comment]
> @C3PablO Looks like `height` is set to zero on one or more elements when the **Layout and spacing** section identifies a layer with autolayout settings. Is that the case? Any chance you could provide view access to a Figma file with the offending instance?

Sure. Thanks for the quick reply. Here is a link to a test file: https://www.figma.com/file/nXebYd8B49xTMY4r0ThYq1/Untitled?node-id=0%3A1&t=ZWEuUIpklzC05Uov-1

**Comment by nathanacurtis** [comment]
@C3PablO I've fixed the issue and you'll see it corrected in the next release (within a week?). I'd not thought of layers associated with boolean properties that'd have no height or width! You also helped me find a few other similar bugs with layout and spacing overlays too. Cheers.
