### ISSUE TITLE
Generate components to allow the user to change the style of pages created by the plugin

### ISSUE THREAD

**Issue by lucacacciarru** [EightShapes/specs-plugin-feedback#41]
## **Is your feature request related to a problem? Please describe.**
It would be great if the user could change the style of the frames generated by the plugin. By default, the plugin renders several pages and elements that use specific design tokens:
- pages have white background 
- the number circles are brown
- the text has a specific color, font, and size
- component container has a grey background 
- etc

This behavior could create some "problems", for example, If the user is working on a component that has grey or white elements, that won't be clearly visible, as you can see in the following screenshots:

![image](https://user-images.githubusercontent.com/86778250/219641526-22ac1a27-8bde-47fc-80ca-1466ae32e605.png)

![image](https://user-images.githubusercontent.com/86778250/219641758-45ba7cae-78c7-4a48-afcb-887d24c21dd5.png)

If the user-generated element has a similar style to the one generated by the plugin, the above problem may happen with all user components. Also, if the user wishes to change the default style of the plugin page, they should do so each time they use the plugin. 

## **Describe the solution you'd like**
To avoid this problem, when the plugin is fired for the first time in a project, it should create Figma components for each element of the plugin output. The instances of these components will be used to build the frames of the plugin. In this way, the user can change the style of the different generated elements and they don't need to change them at any time. There are other plugins that use this approach, one of these plugins is [Table Creator](https://www.figma.com/community/plugin/885838970710285271/Table-Creator)

I made a video to show how it works and what I meant
https://tella.video/tablecreator-showcase-447e

## **Additional context**
I'd like to help you to develop this feature, but unfortunately, I saw the source code of this plugin is not available :(

**Comment by jamesmelzer** [comment]
@lucacacciarru,

You can set individual artwork frames to a system-appropriate background color, such as black. Or, if your entire design system assumes dark backgrounds, you can edit the plugin-created color style `ESDS Spec/Artwork background` to an appropriate style/token from your system. 

cc/ @nathanacurtis

**Comment by nathanacurtis** [comment]
@lucacacciarru 

Thanks for your submitting your request. As @jamesmelzer mentioned, there are a few paths for now for resolving this challenge:

- Manually change the style of the `Artwork` frame, such as applying a color style from your file / design system
- Update the style @jamesmelzer refers to

We've considered using components for some aspects of the plugins output, but have avoided that for now. For example, the `Artwork` frame itself couldn't be a component, for it contains highly variable and unpredictable children including the component being annotated. It _could_ be a component if absolutely positioned inside the frame as a sibling of the annotated component, but that seems impractical.

In the future, I'm also considering configuration settings whereby you'd provide a property / value pair (such as a `mode` prop set to `dark`) and the plugin would color those `Artwork` frames with an alternate, darker background.
