### ISSUE TITLE
🐞 get_componentProperties error

### ISSUE THREAD

**Issue by henrich321** [EightShapes/specs-plugin-feedback#45]
### Description

Whenever I select one of my autolayout frames it spits out the anatomy frame and a tiny "specs" frame with nothing in it, and continues to run until I click cancel.  Is there any debugging I can enable to help resolve?

### Expected behavior

{A clear and concise description of what you expected to happen}

### Screenshot

{If applicable, add screenshots such as the Figma canvas, layer panel or design panel}

### Console log

figma_app.min.js.br:5 unhandled promise rejection: Error: in get_componentProperties: Component set for node has existing errors
(anonymous) @ figma_app.min.js.br:5
printChar @ jsvm-cpp.js.br:9
_fd_write @ jsvm-cpp.js.br:9
$func798 @ jsvm-cpp.wasm.br:0x8380e
$func802 @ jsvm-cpp.wasm.br:0x83aac
$func811 @ jsvm-cpp.wasm.br:0x852b6
$func812 @ jsvm-cpp.wasm.br:0x852d7
$func13 @ jsvm-cpp.wasm.br:0x1210
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6188
(anonymous) @ figma_app.min.js.br:598
Promise.then (async)
c @ figma_app.min.js.br:598
get undefined @ figma_app.min.js.br:598
get undefined @ figma_app.min.js.br:627
(anonymous) @ figma_app.min.js.br:1517
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1517
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1517
(anonymous) @ figma_app.min.js.br:1490
(anonymous) @ figma_app.min.js.br:1347
VPu.e.invokeCallback @ figma_app.min.js.br:598
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func203 @ jsvm-cpp.wasm.br:0x29e7e
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func490 @ jsvm-cpp.wasm.br:0x549a5
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6036
(anonymous) @ figma_app.min.js.br:598
Promise.then (async)
c @ figma_app.min.js.br:598
get undefined @ figma_app.min.js.br:598
get undefined @ figma_app.min.js.br:627
(anonymous) @ figma_app.min.js.br:1517
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1517
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1517
(anonymous) @ figma_app.min.js.br:1490
(anonymous) @ figma_app.min.js.br:1347
VPu.e.invokeCallback @ figma_app.min.js.br:598
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func204 @ jsvm-cpp.wasm.br:0x29fd9
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func624 @ jsvm-cpp.wasm.br:0x6de94
$func138 @ jsvm-cpp.wasm.br:0x13819
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func332 @ jsvm-cpp.wasm.br:0x38d9d
$func172 @ jsvm-cpp.wasm.br:0x25044
$func336 @ jsvm-cpp.wasm.br:0x39ac1
$jsvm_evalCode @ jsvm-cpp.wasm.br:0xb0b8
evalCode @ figma_app.min.js.br:598
evalCodeInternal @ figma_app.min.js.br:628
evalTopLevelCode @ figma_app.min.js.br:629
(anonymous) @ figma_app.min.js.br:1519
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
VEs.runResult @ figma_app.min.js.br:1519
VEs @ figma_app.min.js.br:1517
await in VEs (async)
Chr @ figma_app.min.js.br:1522
(anonymous) @ figma_app.min.js.br:1652
await in (anonymous) (async)
ekt @ figma_app.min.js.br:1652
yap @ figma_app.min.js.br:1652
await in yap (async)
(anonymous) @ figma_app.min.js.br:1652
v3 @ figma_app.min.js.br:2076
(anonymous) @ figma_app.min.js.br:2076
onSelectItem @ figma_app.min.js.br:2076
(anonymous) @ figma_app.min.js.br:1656
(anonymous) @ figma_app.min.js.br:1656
QJd @ figma_app.min.js.br:16
ZJd @ figma_app.min.js.br:16
JJd @ figma_app.min.js.br:16
ZGn @ figma_app.min.js.br:16
CKn @ figma_app.min.js.br:16
(anonymous) @ figma_app.min.js.br:16
qlo @ figma_app.min.js.br:19
$Wn @ figma_app.min.js.br:16
lao @ figma_app.min.js.br:16
Alo @ figma_app.min.js.br:16
geu @ figma_app.min.js.br:16
n @ figma_app.min.js.br:12
figma_app.min.js.br:5     at addAttributesToInstance (PLUGIN_13_SOURCE)
(anonymous) @ figma_app.min.js.br:5
printChar @ jsvm-cpp.js.br:9
_fd_write @ jsvm-cpp.js.br:9
$func798 @ jsvm-cpp.wasm.br:0x8380e
$func896 @ jsvm-cpp.wasm.br:0x8d485
$func804 @ jsvm-cpp.wasm.br:0x84439
$func803 @ jsvm-cpp.wasm.br:0x843fd
$func802 @ jsvm-cpp.wasm.br:0x83a96
$func811 @ jsvm-cpp.wasm.br:0x852b6
$func812 @ jsvm-cpp.wasm.br:0x852d7
$func13 @ jsvm-cpp.wasm.br:0x125a
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6188
(anonymous) @ figma_app.min.js.br:598
Promise.then (async)
c @ figma_app.min.js.br:598
get undefined @ figma_app.min.js.br:598
get undefined @ figma_app.min.js.br:627
(anonymous) @ figma_app.min.js.br:1517
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1517
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1517
(anonymous) @ figma_app.min.js.br:1490
(anonymous) @ figma_app.min.js.br:1347
VPu.e.invokeCallback @ figma_app.min.js.br:598
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func203 @ jsvm-cpp.wasm.br:0x29e7e
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func490 @ jsvm-cpp.wasm.br:0x549a5
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6036
(anonymous) @ figma_app.min.js.br:598
Promise.then (async)
c @ figma_app.min.js.br:598
get undefined @ figma_app.min.js.br:598
get undefined @ figma_app.min.js.br:627
(anonymous) @ figma_app.min.js.br:1517
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1517
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1517
(anonymous) @ figma_app.min.js.br:1490
(anonymous) @ figma_app.min.js.br:1347
VPu.e.invokeCallback @ figma_app.min.js.br:598
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func204 @ jsvm-cpp.wasm.br:0x29fd9
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func624 @ jsvm-cpp.wasm.br:0x6de94
$func138 @ jsvm-cpp.wasm.br:0x13819
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func332 @ jsvm-cpp.wasm.br:0x38d9d
$func172 @ jsvm-cpp.wasm.br:0x25044
$func336 @ jsvm-cpp.wasm.br:0x39ac1
$jsvm_evalCode @ jsvm-cpp.wasm.br:0xb0b8
evalCode @ figma_app.min.js.br:598
evalCodeInternal @ figma_app.min.js.br:628
evalTopLevelCode @ figma_app.min.js.br:629
(anonymous) @ figma_app.min.js.br:1519
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
VEs.runResult @ figma_app.min.js.br:1519
VEs @ figma_app.min.js.br:1517
await in VEs (async)
Chr @ figma_app.min.js.br:1522
(anonymous) @ figma_app.min.js.br:1652
await in (anonymous) (async)
ekt @ figma_app.min.js.br:1652
yap @ figma_app.min.js.br:1652
await in yap (async)
(anonymous) @ figma_app.min.js.br:1652
v3 @ figma_app.min.js.br:2076
(anonymous) @ figma_app.min.js.br:2076
onSelectItem @ figma_app.min.js.br:2076
(anonymous) @ figma_app.min.js.br:1656
(anonymous) @ figma_app.min.js.br:1656
QJd @ figma_app.min.js.br:16
ZJd @ figma_app.min.js.br:16
JJd @ figma_app.min.js.br:16
ZGn @ figma_app.min.js.br:16
CKn @ figma_app.min.js.br:16
(anonymous) @ figma_app.min.js.br:16
qlo @ figma_app.min.js.br:19
$Wn @ figma_app.min.js.br:16
lao @ figma_app.min.js.br:16
Alo @ figma_app.min.js.br:16
geu @ figma_app.min.js.br:16
n @ figma_app.min.js.br:12
figma_app.min.js.br:5     at addAndMarkElement (PLUGIN_13_SOURCE)
(anonymous) @ figma_app.min.js.br:5
printChar @ jsvm-cpp.js.br:9
_fd_write @ jsvm-cpp.js.br:9
$func798 @ jsvm-cpp.wasm.br:0x8380e
$func896 @ jsvm-cpp.wasm.br:0x8d485
$func804 @ jsvm-cpp.wasm.br:0x84439
$func803 @ jsvm-cpp.wasm.br:0x843fd
$func802 @ jsvm-cpp.wasm.br:0x83a96
$func811 @ jsvm-cpp.wasm.br:0x852b6
$func812 @ jsvm-cpp.wasm.br:0x852d7
$func13 @ jsvm-cpp.wasm.br:0x125a
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6188
(anonymous) @ figma_app.min.js.br:598
Promise.then (async)
c @ figma_app.min.js.br:598
get undefined @ figma_app.min.js.br:598
get undefined @ figma_app.min.js.br:627
(anonymous) @ figma_app.min.js.br:1517
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1517
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1517
(anonymous) @ figma_app.min.js.br:1490
(anonymous) @ figma_app.min.js.br:1347
VPu.e.invokeCallback @ figma_app.min.js.br:598
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func203 @ jsvm-cpp.wasm.br:0x29e7e
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func490 @ jsvm-cpp.wasm.br:0x549a5
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6036
(anonymous) @ figma_app.min.js.br:598
Promise.then (async)
c @ figma_app.min.js.br:598
get undefined @ figma_app.min.js.br:598
get undefined @ figma_app.min.js.br:627
(anonymous) @ figma_app.min.js.br:1517
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1517
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1517
(anonymous) @ figma_app.min.js.br:1490
(anonymous) @ figma_app.min.js.br:1347
VPu.e.invokeCallback @ figma_app.min.js.br:598
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func204 @ jsvm-cpp.wasm.br:0x29fd9
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func624 @ jsvm-cpp.wasm.br:0x6de94
$func138 @ jsvm-cpp.wasm.br:0x13819
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func332 @ jsvm-cpp.wasm.br:0x38d9d
$func172 @ jsvm-cpp.wasm.br:0x25044
$func336 @ jsvm-cpp.wasm.br:0x39ac1
$jsvm_evalCode @ jsvm-cpp.wasm.br:0xb0b8
evalCode @ figma_app.min.js.br:598
evalCodeInternal @ figma_app.min.js.br:628
evalTopLevelCode @ figma_app.min.js.br:629
(anonymous) @ figma_app.min.js.br:1519
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
VEs.runResult @ figma_app.min.js.br:1519
VEs @ figma_app.min.js.br:1517
await in VEs (async)
Chr @ figma_app.min.js.br:1522
(anonymous) @ figma_app.min.js.br:1652
await in (anonymous) (async)
ekt @ figma_app.min.js.br:1652
yap @ figma_app.min.js.br:1652
await in yap (async)
(anonymous) @ figma_app.min.js.br:1652
v3 @ figma_app.min.js.br:2076
(anonymous) @ figma_app.min.js.br:2076
onSelectItem @ figma_app.min.js.br:2076
(anonymous) @ figma_app.min.js.br:1656
(anonymous) @ figma_app.min.js.br:1656
QJd @ figma_app.min.js.br:16
ZJd @ figma_app.min.js.br:16
JJd @ figma_app.min.js.br:16
ZGn @ figma_app.min.js.br:16
CKn @ figma_app.min.js.br:16
(anonymous) @ figma_app.min.js.br:16
qlo @ figma_app.min.js.br:19
$Wn @ figma_app.min.js.br:16
lao @ figma_app.min.js.br:16
Alo @ figma_app.min.js.br:16
geu @ figma_app.min.js.br:16
n @ figma_app.min.js.br:12
figma_app.min.js.br:5     at P (PLUGIN_13_SOURCE)
(anonymous) @ figma_app.min.js.br:5
printChar @ jsvm-cpp.js.br:9
_fd_write @ jsvm-cpp.js.br:9
$func798 @ jsvm-cpp.wasm.br:0x8380e
$func896 @ jsvm-cpp.wasm.br:0x8d485
$func804 @ jsvm-cpp.wasm.br:0x84439
$func803 @ jsvm-cpp.wasm.br:0x843fd
$func802 @ jsvm-cpp.wasm.br:0x83a96
$func811 @ jsvm-cpp.wasm.br:0x852b6
$func812 @ jsvm-cpp.wasm.br:0x852d7
$func13 @ jsvm-cpp.wasm.br:0x125a
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6188
(anonymous) @ figma_app.min.js.br:598
Promise.then (async)
c @ figma_app.min.js.br:598
get undefined @ figma_app.min.js.br:598
get undefined @ figma_app.min.js.br:627
(anonymous) @ figma_app.min.js.br:1517
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1517
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1517
(anonymous) @ figma_app.min.js.br:1490
(anonymous) @ figma_app.min.js.br:1347
VPu.e.invokeCallback @ figma_app.min.js.br:598
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func203 @ jsvm-cpp.wasm.br:0x29e7e
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func490 @ jsvm-cpp.wasm.br:0x549a5
$jsvm_runMicrotasksAndAutorelease @ jsvm-cpp.wasm.br:0x6036
(anonymous) @ figma_app.min.js.br:598
Promise.then (async)
c @ figma_app.min.js.br:598
get undefined @ figma_app.min.js.br:598
get undefined @ figma_app.min.js.br:627
(anonymous) @ figma_app.min.js.br:1517
Promise.then (async)
(anonymous) @ figma_app.min.js.br:1517
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
cb @ figma_app.min.js.br:1517
(anonymous) @ figma_app.min.js.br:1490
(anonymous) @ figma_app.min.js.br:1347
VPu.e.invokeCallback @ figma_app.min.js.br:598
70556 @ jsvm-cpp.js.br:9
_emscripten_asm_const_int @ jsvm-cpp.js.br:9
$func20 @ jsvm-cpp.wasm.br:0x59d8
$func138 @ jsvm-cpp.wasm.br:0x136e3
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func369 @ jsvm-cpp.wasm.br:0x3efdc
$func204 @ jsvm-cpp.wasm.br:0x29fd9
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func147 @ jsvm-cpp.wasm.br:0x1709c
$func624 @ jsvm-cpp.wasm.br:0x6de94
$func138 @ jsvm-cpp.wasm.br:0x13819
$func147 @ jsvm-cpp.wasm.br:0x152eb
$func147 @ jsvm-cpp.wasm.br:0x17216
$func332 @ jsvm-cpp.wasm.br:0x38d9d
$func172 @ jsvm-cpp.wasm.br:0x25044
$func336 @ jsvm-cpp.wasm.br:0x39ac1
$jsvm_evalCode @ jsvm-cpp.wasm.br:0xb0b8
evalCode @ figma_app.min.js.br:598
evalCodeInternal @ figma_app.min.js.br:628
evalTopLevelCode @ figma_app.min.js.br:629
(anonymous) @ figma_app.min.js.br:1519
n @ figma_app.min.js.br:12
setTimeout (async)
(anonymous) @ figma_app.min.js.br:12
VEs.runResult @ figma_app.min.js.br:1519
VEs @ figma_app.min.js.br:1517
await in VEs (async)
Chr @ figma_app.min.js.br:1522
(anonymous) @ figma_app.min.js.br:1652
await in (anonymous) (async)
ekt @ figma_app.min.js.br:1652
yap @ figma_app.min.js.br:1652
await in yap (async)
(anonymous) @ figma_app.min.js.br:1652
v3 @ figma_app.min.js.br:2076
(anonymous) @ figma_app.min.js.br:2076
onSelectItem @ figma_app.min.js.br:2076
(anonymous) @ figma_app.min.js.br:1656
(anonymous) @ figma_app.min.js.br:1656
QJd @ figma_app.min.js.br:16
ZJd @ figma_app.min.js.br:16
JJd @ figma_app.min.js.br:16
ZGn @ figma_app.min.js.br:16
CKn @ figma_app.min.js.br:16
(anonymous) @ figma_app.min.js.br:16
qlo @ figma_app.min.js.br:19
$Wn @ figma_app.min.js.br:16
lao @ figma_app.min.js.br:16
Alo @ figma_app.min.js.br:16
geu @ figma_app.min.js.br:16
n @ figma_app.min.js.br:12
figma_app.min.js.br:5     at <anonymous> (PLUGIN_13_SOURCE)

### Additional context

{Add any other context about the problem here}

**Comment by nathanacurtis** [comment]
@henrich321 Thanks for your submission. I've seen the `get_componentProperties: Component set for node has existing errors` error you triggered before. In cases I've observed, it's triggered by a component set that has "missing combinations", such as a checkbox that has a variant for checked=true and a variant for error=true but not a variant for checked=true AND error=true. I already have a few defensive measures in place to prevent it. 

It'll be difficult or impossible for me to diagnose what's going on with your case without access to the Figma objects. Any chance you could provide me with view access to a simple file with your selected item(s) included?

**Comment by henrich321** [comment]
I empathize, unfortunately I cannot share this file.  I do have components that aren’t “fully complete” as it were.  Let me see if I can make something reproducible in small form I can share.

**Comment by henrich321** [comment]
Okay managed to extract it out.  It is indeed a variant with a missing property.  Here's a figma file that demonstrates it if you try and run on the 

https://www.figma.com/file/SeLiwxwV3DwPNuN0YBROfx/Public-EightSpecs-bug?node-id=0%3A1&t=I4cPxNmwZn1NM67A-1

Thanks!

**Comment by nathanacurtis** [comment]
@henrich321 

Upon inspection, an instance with invalid property definitions throws an error when variants are missing properties. This exception breaks many multiple plugin features, and may take time to fix.

Quick fix for you: fix your errors. 🙃

I'll still prioritize this pretty high on my list. Thanks for submitting!

![image](https://user-images.githubusercontent.com/1165904/221707762-c1e02ea7-8348-4554-ac83-e504f530ce2e.png)

**Comment by nathanacurtis** [comment]
Fixed and will be included in the next release.

**Comment by henrich321** [comment]
Awesome, thx!
