### ISSUE TITLE
The Plugin encountered an error

### ISSUE THREAD

**Issue by blv-Adrian-Lombera** [EightShapes/specs-plugin-feedback#61]
### Description

{A clear and concise description of what the bug is}

### Defect log

{Before running the plugin, in Figma:
* Select Plugins > Development > Open console
* Run the plugin
* Paste the text or screenshot of error displayed in the console log here}

### Steps to reproduce

1. Format `layer` with `style` text style...
2. Add `16` autolayout spacing to `layer` on `variant` variant...
3. Click on '....'
4. Scroll down to '....'
5. Run the plugin
6. The `section` of specs shows X when I expected to see Y

### Screenshot

{If applicable, add screenshots such as the Figma canvas, layer panel or design panel}

### Additional context

{Add any other context about the problem here}

**Comment by nathanacurtis** [comment]
@blv-Adrian-Lombera Do you plan to add any descriptive information about the error you found? Currently, the issue description is the template content. Thanks :)
